### ISSUE TITLE
Multiple RF and PLC interfaces

### ISSUE THREAD

**Issue by Amrican10** [39617/contiki_multiple_interface#3]
@ticosta @cprates Currently, I am working with Whitefield platform using both NS3 and Contiki repos.

For a hybrid RF and PLC network, Contiki nodes should have at least two interfaces to work well with routing (RPL). 
I realized that this repo considers only certain AVR. Could you add some features such that each node (sky cc2420 for example) has two interfaces for each technology.

**Comment by cprates** [comment]
Hi @Amrican10, the support for multiple interfaces in its current state doesn't work with RPL enabled.
From what I remember we decided to not support RPL at the time because it's a major piece of work on its own mainly because it manages its own neighbours table if I not mistaken
